// Evidence: git da5356d^, deleted by da5356d; package version 1.1.0.
export const legacyRunCsgoFiles: ReadonlyArray<{ path: string; sha256: string; version: string }> = [
  // git 9202b779: bundled 1.cfg after ensureBaseCfgLoadsNoRandomBots (exact generated bytes).
  { path: "csgo/cfg/1.cfg", sha256: "63FF12F4FFDDB7F5F9A4B2ED1BA07AE10273165484DDFCEF78BCD809465AC30A", version: "1.2.10" },
  {
    "path": "de_ancient.bat",
    "sha256": "D3B70878F449512FB3A7EE47B56DB3B57BE137860713009FE1D2B4E1FFA7146F",
    "version": "1.1.0"
  },
  {
    "path": "de_ancient.ps1",
    "sha256": "96769C64803315CBDD94FC43C6311F46E6D099ADEE29DC3E56497837A2C88695",
    "version": "1.1.0"
  },
  {
    "path": "de_anubis.bat",
    "sha256": "025E34543E10D4B2C0E73A502E3C7BAE67F8A3ECDD6C29800C58103480161DC3",
    "version": "1.1.0"
  },
  {
    "path": "de_anubis.ps1",
    "sha256": "F03DFEB8F8B5F0C8356DED2CCE98A9AD92AAC4123D30A8D4723960DF3280D30F",
    "version": "1.1.0"
  },
  {
    "path": "de_cache.bat",
    "sha256": "E044F4B7486727337AC9DF5D88CF406E6E180BB4FDCC53A553F4FA2355622226",
    "version": "1.1.0"
  },
  {
    "path": "de_cache.ps1",
    "sha256": "DCC7B32D9AF1741EC4FFF58E8E013445A52E0B6471A7CF584BC73339E80D8ED1",
    "version": "1.1.0"
  },
  {
    "path": "de_dust2.bat",
    "sha256": "A3D2B0D89AE00F9F71BF9DA197667BD50BD79C8B87D7A50E50B0C0AB33AA77E9",
    "version": "1.1.0"
  },
  {
    "path": "de_dust2.ps1",
    "sha256": "CD39729A1688F8DC3A9F3350CB0F7292204FDE1C89F6A187CC4E642D1C6D99C8",
    "version": "1.1.0"
  },
  {
    "path": "de_inferno.bat",
    "sha256": "EC133C797F6F65ED5C8AD06D9CD00241B6D07F65D2AA6ABA325585BA9D7CCB4B",
    "version": "1.1.0"
  },
  {
    "path": "de_inferno.ps1",
    "sha256": "7C2D162A29D76C257D92225BB0CE7CA70917CD01CE0F4730AE813487FEE7EDE0",
    "version": "1.1.0"
  },
  {
    "path": "de_mirage.bat",
    "sha256": "069ECE21B6DEAB119B37FE94E995C9F0FB6FF7B1586FA80F41BF423B3547EFB8",
    "version": "1.1.0"
  },
  {
    "path": "de_mirage.ps1",
    "sha256": "6BC7121F359560D4338743FD010B0A4389C1F5A9C28C2A0B38710EB445293589",
    "version": "1.1.0"
  },
  {
    "path": "de_nuke.bat",
    "sha256": "10F49E854737EF176BCA7D79C1CC0A0AC75A5B373A6E9D27D4BC183DE31D0904",
    "version": "1.1.0"
  },
  {
    "path": "de_nuke.ps1",
    "sha256": "9F3BDF015690411532A696A6C8A02B45DD2995CFDDB9C4A1DC35DB586F223AAB",
    "version": "1.1.0"
  },
  {
    "path": "de_overpass.bat",
    "sha256": "787E20A7536B80A8FDDF8ADBC27B26464B01EBA2AF879B0FB67B4B2BEA8FC4F1",
    "version": "1.1.0"
  },
  {
    "path": "de_overpass.ps1",
    "sha256": "56149BA8761B13713193187A95C40FCF59DE0AB581B4A6F389A47916CC9720C4",
    "version": "1.1.0"
  },
  {
    "path": "de_train.bat",
    "sha256": "4DF19DB4F31F5447DB7813342E092A5EE13A96921470C7E7C31B9CFA103A245C",
    "version": "1.1.0"
  },
  {
    "path": "de_train.ps1",
    "sha256": "F6E97547C931894AE7B1A31C52756C5F39E656A8266CC9C14907FC84E7951381",
    "version": "1.1.0"
  },
  {
    "path": "de_vertigo.bat",
    "sha256": "5B1AEF740677D35978613938839F6B4C651B7C220A9589CCE7ADF60CC29D04CC",
    "version": "1.1.0"
  },
  {
    "path": "de_vertigo.ps1",
    "sha256": "CB3A3CC9A8C014CDDC8652627C41745C990C851957E9DF671CC63E07B14AE992",
    "version": "1.1.0"
  }
];
